name: creche_cloud
description: "Empowering Early Childhood Development in South Africa"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.0.2+1
  get: ^4.6.6
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.3.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  web: ^0.5.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  sidebarx: ^0.17.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/doodles/
    - assets/logos/

  # Custom fonts can be added here when needed
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700